[build]
  # Build command - das richtige Script für Production
  command = "npm run build:netlify"
  
  # Publish directory - wo die Build-Dateien liegen
  publish = "build"
  
  # Environment variables für Build
  [build.environment]
    NODE_VERSION = "22"

# Redirect rules für SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 